### ISSUE TITLE
Abstract review

### ISSUE THREAD

**Issue by 0MarrkvI0** [Kristian-Lacko/Clanok-MIP#1]
Your implementation of abstracts is excellently written, and it is obvious that you are knowledgeable about the subject. Three additional websites are excellent starting points. Have a nice day. Stay FIIT.

**Comment by Kristian-Lacko** [comment]
Thank you very much for your review, I'm glad you liked the fact I had 3 additional articles and links to them. I hope you have an amazing day as well. You stay FIIT-er!!!
